### ISSUE TITLE
getDefaultTexture() in EnemyModel does not exist

### ISSUE THREAD

**Issue by ronnie-dumesh** [BryanGraeser/fallen-flame#29]
Currently enemyModel.getDefaultTexture() returns a string "enemy-walking". This crashes the program with a null-pointer error. This has been temporarily remedied with it having return the "player" texture. This is the error stack. 

Exception in thread "LWJGL Application" java.lang.NullPointerException
	at com.fallenflame.game.physics.obstacle.SimpleObstacle.setTexture(SimpleObstacle.java:770)
	at com.fallenflame.game.EnemyModel.initialize(EnemyModel.java:34)
	at com.fallenflame.game.LevelController.populate(LevelController.java:289)
	at com.fallenflame.game.GameEngine.reset(GameEngine.java:222)
	at com.fallenflame.game.GDXRoot.exitScreen(GDXRoot.java:108)
	at com.fallenflame.game.LoadingMode.render(LoadingMode.java:327)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by BryanGraeser** [comment]
Solution here: #33 

Once you merge this PR, you will just need to be sure you properly create EnemyJSON's. Model them like the existing player JSON. and the texture name you should use is "enemy".

For the future, look at `assets.json` and you can see what textures are loaded and what they are called. You can add whatever textures you need loaded here (as long as you add a corresponding texture to the texture folder).
