### ISSUE TITLE
Search-algorithm memory error 

### ISSUE THREAD

**Issue by ronnie-dumesh** [BryanGraeser/fallen-flame#30]
Possible to see in add-enemies branch 

In my BFS algorithm, I have Hashset<Coordinate> visited. When I go through the BFS, I add the position of the visited tiles to visited. When I run the game, it instantly freezes and crashes after some time. (You have to let the game crash on its own to reproduce the error, not close it). Make sure line 182 of LightController is commented out as well.

I think this is simply an unavoidable consequence of using a HashSet here. How Lab2 implemented visited tiles was through "marking". See getMoveAlongPathToGoalTile() description. http://www.cs.cornell.edu/courses/cs3152/2020sp/labs/program2/

We can implement this "marking" functionality in LevelModel and hopefully avoid this issue. Perhaps I can also try your BFS algorithm here as it might be with my implementation. Being that we're probably going to switch to an A*-type search algorithm anyway, we might want to have an option that allows easy transition to that.

Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.OutOfMemoryError: Java heap space
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:135)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:663)
	at java.util.HashMap.put(HashMap.java:612)
	at java.util.HashSet.add(HashSet.java:220)
	at com.fallenflame.game.AIController.getMoveAlongPathToGoalTile(AIController.java:272)
	at com.fallenflame.game.AIController.getAction(AIController.java:106)
	at com.fallenflame.game.LevelController.update(LevelController.java:382)
	at com.fallenflame.game.GameEngine.update(GameEngine.java:283)
	at com.fallenflame.game.GameEngine.render(GameEngine.java:337)
	at com.badlogic.gdx.Game.render(Game.java:46)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:233)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:128)

**Comment by BryanGraeser** [comment]
I think marking wouldn't be too difficult. We would just have to call some sort of levelmodel.clearMarkings() when an AIController is done using it.

Have you looked into A* Search yet?

**Comment by BryanGraeser** [comment]
@ronnie-dumesh is adding marking functionality to levelmodel.

**Comment by BryanGraeser** [comment]
Should be resolved by #46
